import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script"; 

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
      <Script src='/Users/solomon/development/python/gh-digital_asset/next-app/sddac-app/node_modules/flowbite/dist/flowbite.js' />

</body>
    </html>
  );
}


